apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  template:
    spec:
      containers:
      - name: orders-service
        image: nachomdo/orders-service:10.0.8
        startupProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /v1/healthcheck
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3

